#!/bin/env bash

PLUGINS=$(readlink -m "$0/../share/insights-policy-check/plugins")

export ANSIBLE_CALLBACK_PLUGINS=${PLUGINS}/callback_plugins
export ANSIBLE_ACTION_PLUGINS=${PLUGINS}/action_plugins
export ANSIBLE_LIBRARY=${PLUGINS}/library
export ANSIBLE_CALLBACK_WHITELIST=notify_insights

ansible-playbook --check "$@"

