---
- hosts: all
  become: yes
  tasks:

  - stat:
        path: /etc/passwd-
    register: passwd_minus_task

  - name: "SCORED | 6.1.6 | PATCH | Ensure permissions on /etc/passwd- are configured"
    when: passwd_minus_task.stat.exists
    file:
        dest: /etc/passwd-
        owner: root
        group: root
        mode: 0600
    tags:
        - level1
        - level2
        - patch
        - rule_6.1.6
