---
# This playbook
#  ensures that 'redhat-access-insights' is installed
#  ensures that system is registered with Insights service
#  if insights_display_name
#    ensure that system is registered with insights_display_name
#  ensures that Insights system_id fact collector is installed
#  ensures that the permissions on /etc/redhat-access-insights/machine-id,
#    which contains the system_id, are such that normal users can read it.
#
- hosts: all
  become: yes
  tasks:

  - name: need libselinux-python to run ansible on SELinux
    yum:
      name: libselinux-python
      state: present
    become: yes
    when: ansible_distribution == "RedHat" or ansible_distribution == "Fedora"

  - name: Install Red Hat Access Insights Client
    yum:
      name: redhat-access-insights
      state: present
    become: yes

  - name: Check status of Insights .register file
    stat: path=/etc/redhat-access-insights/.registered
    become: yes
    register: reg_file_task

  - name: Unregister if we are setting the display_name, and we have already registered
    command: redhat-access-insights --unregister
    when:
      - insights_display_name is defined
      - reg_file_task.stat.exists == true
    become: yes

  # Only register if this system hasn't been registered before
  - name: Register to the Red Hat Access Insights Service
    command: redhat-access-insights --register {{ '--display-name='+insights_display_name if insights_display_name is defined else '' }} creates=/etc/redhat-access-insights/.registered
    become: yes


  - name: Change permissions of Insights Config directory so that Insights System ID can be read
    file:
      path: /etc/redhat-access-insights
      mode: og=rx
    become: yes

  - name: Change permissions of machine_id file so that Insights System ID can be read
    file:
      path: /etc/redhat-access-insights/machine-id
      mode: og=r
    become: yes


  - name: Create directory for ansible custom facts
    file:
      state: directory
      recurse: yes
      path: /etc/ansible/facts.d
    become: yes

  - name: Install custom insights fact
    copy:
      src: insights.fact
      dest: /etc/ansible/facts.d
      mode: a+x
    become: yes
