---
# This playbook installs Ansible on a RHEL7 target from the 'extras' repo
- hosts: all
  become: yes
  tasks:

    # this only works on RHEL6
    - name: only works on RHEL 6
      assert:
        that:
          - ansible_distribution == "RedHat"
          - ansible_distribution_major_version == "7"

    - name: Enable the 'extras' repo
      command: subscription-manager repos --enable=rhel-7-server-extras-rpms

    - name: Install Ansible
      package:
        name: ansible
