- hosts: all
  user: root
  tasks:

  # I had expected the following to work as a way to test that fips_mode was enabled
  # run the sysctl module in check mode and used the "not changed" status to tell if
  # in fips mode or not.

  - name: Are we in crypto.fips_enabled
    sysctl:
      key: crypto.fips_enabled
      value: 1
    check_mode: yes
    register: sysctl_fips_mode_task

  - debug: msg="What is not sysctl_fips_mode_task.changed {{ not sysctl_fips_mode_task.changed  }}"

  - debug: msg="Not not sysctl_fips_mode_task.changed"
    when: not not sysctl_fips_mode_task.changed

  - debug: msg="Yes not sysctl_fips_mode_task.changed"
    when: not sysctl_fips_mode_task.changed
