- hosts: all
  user: root
  tasks:

  - name: Update grub entries for current kernel
    command: grubby --update-kernel=/boot/vmlinuz-{{ ansible_kernel }} --remove-args="fips boot"

  - name: Reboot
    shell: sleep 2 && reboot
    async: 1
    poll: 0
    ignore_errors: true
    when: not ansible_check_mode
