- hosts: all
  user: root
  tasks:

  - name: Reboot
    shell: sleep 2 && reboot
    async: 1
    poll: 0
    ignore_errors: true
    when: not ansible_check_mode   # can't run async jobs in check_mode

  - name: Wait for system to boot up
    local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=15 timeout=300
    become: false
